export const suppliers = [
  {"value": 10, "label": "ABACO (10)"},
  {"value": 11, "label": "ABASTECER SEGURIDAD (11)"},
  {"value": 12, "label": "ALFREDO ALVAREZ (12)"},
  {"value": 13, "label": "ALIAFOR (13)"},
  {"value": 14, "label": "ALSEC (14)"},
  {"value": 15, "label": "ANCLAJES Y SERVICIOS (15)"},
  {"value": 16, "label": "APEZTEGUIA (16)"},
  {"value": 17, "label": "BAEZ (17)"},
  {"value": 18, "label": "BOSCH (18)"},
  {"value": 19, "label": "CAMITS (19)"},
  {"value": 20, "label": "CASA LEON (20)"},
  {"value": 21, "label": "CASA LOUREIRO (21)"},
  {"value": 22, "label": "CATINARI (22)"},
  {"value": 23, "label": "CORTIFRIL (23)"},
  {"value": 24, "label": "CRIMARAL (24)"},
  {"value": 25, "label": "DALMASO (25)"},
  {"value": 26, "label": "DEPER (26)"},
  {"value": 27, "label": "DISTHESA (27)"},
  {"value": 28, "label": "DISTROPAR (28)"},
  {"value": 29, "label": "ERAM (29)"},
  {"value": 30, "label": "ESLINGAR (30)"},
  {"value": 31, "label": "GAN MAR (31)"},
  {"value": 32, "label": "GIORDANO (32)"},
  {"value": 33, "label": "HAMILTON (33)"},
  {"value": 34, "label": "HOFER (34)"},
  {"value": 35, "label": "INDHOR (35)"},
  {"value": 36, "label": "ITURRIA (36)"},
  {"value": 37, "label": "KAIKEN (37)"},
  {"value": 38, "label": "KALYDON (38)"},
  {"value": 39, "label": "KLEE PLAT (39)"},
  {"value": 40, "label": "LEITEN (40)"},
  {"value": 41, "label": "MACROMAQ (41)"},
  {"value": 42, "label": "MAT.ELECTRICOS (42)"},
  {"value": 43, "label": "MAT.GEORGIA (43)"},
  {"value": 44, "label": "MET.ROSARIO (44)"},
  {"value": 45, "label": "MORANO (45)"},
  {"value": 46, "label": "MOTORARG (46)"},
  {"value": 47, "label": "MULTIPLASTIKA (47)"},
  {"value": 48, "label": "NOTRICA (48)"},
  {"value": 49, "label": "PAIMUN (49)"},
  {"value": 50, "label": "POLO (50)"},
  {"value": 51, "label": "REINER (51)"},
  {"value": 52, "label": "SAL-BOM (52)"},
  {"value": 53, "label": "SIMPA (53)"},
  {"value": 54, "label": "SINIS (54)"},
  {"value": 55, "label": "TEXWORK (55)"},
  {"value": 56, "label": "VACCA (56)"},
  {"value": 57, "label": "AGROREDES (57)"},
  {"value": 58, "label": "ALFA (58)"},
  {"value": 59, "label": "ARGENSAFE (59)"},
  {"value": 60, "label": "B Y A ARGENTINA (60)"},
  {"value": 61, "label": "BENITEZ ELOY (61)"},
  {"value": 62, "label": "BREAK FIRE S.R.L. (62)"},
  {"value": 63, "label": "BULONERA BURZACO (63)"},
  {"value": 64, "label": "BULONFER (64)"},
  {"value": 65, "label": "CERNADAS (65)"},
  {"value": 66, "label": "DAF (66)"},
  {"value": 67, "label": "DIST,DISTOR (67)"},
  {"value": 68, "label": "ELECTROFER (68)"},
  {"value": 69, "label": "ELECTROMAQ (69)"},
  {"value": 70, "label": "FER PAK (70)"},
  {"value": 71, "label": "GERDAU (71)"},
  {"value": 72, "label": "GRAMMA SEGURIDAD (72)"},
  {"value": 73, "label": "HELIX (73)"},
  {"value": 74, "label": "HIDROVENT (74)"},
  {"value": 75, "label": "LANDAU (75)"},
  {"value": 76, "label": "LASSO (76)"},
  {"value": 77, "label": "LUBE SEGURIDAD (77)"},
  {"value": 78, "label": "MANUF. DEL PLASTICO (78)"},
  {"value": 79, "label": "MEGAMAQ (79)"},
  {"value": 80, "label": "NETOOLS (80)"},
  {"value": 81, "label": "OLIVARES (81)"},
  {"value": 82, "label": "PROAR (82)"},
  {"value": 83, "label": "PROTEC (83)"},
  {"value": 84, "label": "PULQUI (84)"},
  {"value": 85, "label": "RINOTEC (85)"},
  {"value": 86, "label": "ROVIMAR (86)"},
  {"value": 87, "label": "ROSSANA (87)"},
  {"value": 88, "label": "SIVAR / HACHE (88)"},
  {"value": 89, "label": "STARTEX (89)"},
  {"value": 90, "label": "STEEL ROPES (90)"},
  {"value": 91, "label": "SUPERIZAJE (91)"},
  {"value": 92, "label": "SURPROTEC (92)"},
  {"value": 93, "label": "SURPROWORK (93)"},
  {"value": 94, "label": "TEMUCO (94)"},
  {"value": 95, "label": "URAR (95)"},
  {"value": 96, "label": "VALPER (96)"},
  {"value": 97, "label": "VH DISTRIBUCIONES (97)"},
  {"value": 98, "label": "KAGEN (98)"},
  {"value": 99, "label": "LAVOC (99)"},
  {"value": 101, "label": "HEFER (101)"},
  {"value": 104, "label": "TOPASOL (104)"},
  {"value": 105, "label": "JORGE RODAMIENTOS (105)"},
  {"value": 102, "label": "VANESA - MOISES (102)"},
  {"value": 103, "label": "HERPACO (103)"},
  {"value": 106, "label": "PROFEIN(106)"},
  {"value": 107, "label": "EL RAPIDO (107)"},
  {"value": 108, "label": "OMAHA (108)"},
  {"value": 109, "label": "BARBUY TEAM(109)"},
  {"value": 110, "label": "STEPANEK REVOCADORA (110)"},
  {"value": 111, "label": "EL VIEJO WATT (111)"},
  {"value": 114, "label": "KEE GO STANLEY (114)"},
]
